### ISSUE TITLE
Getting issue while running main.py

### ISSUE THREAD

**Issue by Karthik1904** [woldemarg/unstructured_data_post#1]
Greetings for the post:

Please help solving below:

Traceback (most recent call last):
  File "main.py", line 87, in <module>
    for i, img in enumerate(map(make_df_image, [tabula_df, camelot_df])):
  File "main.py", line 34, in make_df_image
    dfi.export(table, tmp.name, max_cols=max_cols, max_rows=max_rows)
  File "/opt/anaconda3/lib/python3.7/site-packages/dataframe_image/_pandas_accessor.py", line 24, in export
    return _export(obj, filename, fontsize, max_rows, max_cols, table_conversion, chrome_path)
  File "/opt/anaconda3/lib/python3.7/site-packages/dataframe_image/_pandas_accessor.py", line 38, in _export
    if df.shape[0] > MAX_ROWS and max_rows is None:
AttributeError: 'list' object has no attribute 'shape'

**Comment by woldemarg** [comment]
make_df_image is just a helper function to draw dataframe as an image. Those error means that your argument to it is not a pandas dataframe, but rather a list. Pls, double check it.

**Comment by Karthik1904** [comment]
tabula_df was a list dataframes, I'm able to fix it by adding [0] at end. Thank you.

tabula_df = (tabula.read_pdf(PDF, stream=True, pages="all"))[0]
